databaseChangeLog:
  - changeSet:
      id: 3.20.22
      author: GraviteeSource Team
      changes:
        - modifyDataType:
            tableName: ${gravitee_prefix}notification_templates
            columnName: description
            newDataType: nvarchar(512)
