databaseChangeLog:
  - changeSet:
      id: 3.18.0
      author: GraviteeSource Team
      changes:
        - addColumn:
            tableName: ${gravitee_prefix}alert_triggers
            columns:
              - column:
                  name: environment_id
                  type: nvarchar(64)
        - addColumn:
              tableName: ${gravitee_prefix}audits
              columns:
                  - column:
                        name: organization_id
                        type: nvarchar(64)
                  - column:
                        name: environment_id
                        type: nvarchar(64)
