databaseChangeLog:
  - changeSet:
      id: 3.20.24
      author: GraviteeSource Team
      changes:
        - modifyDataType:
            tableName: ${gravitee_prefix}flows
            columnName: name
            newDataType: nvarchar(256)
