version: 2.1
jobs:
  emptyjob:
      docker:
          - image: cimg/base:stable
      steps:
          - run:
                command: echo empty job
workflows:
  build:
    when:
      not: true
    jobs:
      - emptyjob