databaseChangeLog:
  - changeSet:
      id: 3.15.14
      author: GraviteeSource Team
      changes:
        - createIndex:
            indexName: idx_${gravitee_prefix}pages_by_order
            columns:
              - column:
                  name: order
                  type: int
            tableName: ${gravitee_prefix}pages
        - createIndex:
            indexName: idx_${gravitee_prefix}pages_by_type
            columns:
              - column:
                  name: type
                  type: nvarchar(64)
            tableName: ${gravitee_prefix}pages
        - createIndex:
            indexName: idx_${gravitee_prefix}pages_refid_reftype
            columns:
              - column:
                  name: reference_id
                  type: nvarchar(64)
              - column:
                  name: reference_type
                  type: nvarchar(64)
            tableName: ${gravitee_prefix}pages
        - createIndex:
            indexName: idx_${gravitee_prefix}pages_parent_type
            columns:
              - column:
                  name: parent_id
                  type: nvarchar(64)
              - column:
                  name: type
                  type: nvarchar(64)
            tableName: ${gravitee_prefix}pages
        - createIndex:
            indexName: idx_${gravitee_prefix}pages_p_n_t_ri_rt
            columns:
              - column:
                  name: parent_id
                  type: nvarchar(64)
              - column:
                  name: name
                  type: nvarchar(64)
              - column:
                  name: type
                  type: nvarchar(64)
              - column:
                  name: reference_id
                  type: nvarchar(64)
              - column:
                  name: reference_type
                  type: nvarchar(64)
            tableName: ${gravitee_prefix}pages
        - dropNotNullConstraint:
            tableName: ${gravitee_rate_limit_prefix}ratelimit
            columnName: subscription
            columnDataType: nvarchar(64)
