databaseChangeLog:
  - changeSet:
      id: 3.19.19
      author: GraviteeSource Team
      changes:
        - modifyDataType:
            tableName: ${gravitee_prefix}notification_templates
            columnName: title
            newDataType: nvarchar(256)
