{{ if and .Values.api.federation.enabled .Values.apim.managedServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-{{ template "apim.serviceAccount" . }}-hazelcast-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
      - pods
      - nodes
      - services
    verbs:
      - get
      - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-{{ .Release.Name }}-hazelcast-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-{{ template "apim.serviceAccount" . }}-hazelcast-role
subjects:
  - kind: ServiceAccount
    name: {{ template "apim.serviceAccount" . }}
    namespace: {{ .Release.Namespace | quote }}
{{ end }}
