databaseChangeLog:
  - changeSet:
      id: 3.19.7
      author: GraviteeSource Team
      changes:
        # ################
        # Flows Changes
        # ################
        - modifyDataType:
            tableName: ${gravitee_prefix}flows
            columnName: condition
            newDataType: nvarchar(512)
