apiVersion: v1
name: apim
# Also update CHANGELOG.md
version: 4.5.0
appVersion: 4.5.0
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/  helm/graviteeio/apim?modal=changelog
  ###########
  # WARNING #
  ###########
  # "changes" must be the last section in this file, because a CI job clean it after each release
  ###########
  artifacthub.io/changes: |
    - kind: fixed
      description: 'Fix cloud configuration: avoid empty secret generation and fix example in value.yaml'
    - kind: fixed
      description: 'Fix cloud configuration: avoid empty volume mount'
    - kind: fixed
      description: 'Split hazelcast config for cluster and cache'
    - kind: fixed
      description: 'Add support of SSL keystore secret'
      links:
        - name: Github Issue
          url: https://github.com/gravitee-io/issues/issues/9854
    - kind: fixed
      description: 'Handle annotations for nginx ingress'
      links:
        - name: Github Issue
          url: https://github.com/gravitee-io/issues/issues/9831
    - kind: fixed
      description: 'Add service account to UI and portal components'
      links:
        - name: Github Issue
          url: https://github.com/gravitee-io/issues/issues/10057