apiVersion: v1
name: apim
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 3.18.0
appVersion: 3.18.0
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim?modal=changelog
  artifacthub.io/changes: |
    - Change the versioning
