apiVersion: v1
name: apim
# Also update CHANGELOG.md
version: 4.6.0-alpha.2
appVersion: 4.6.0-alpha.2
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim?modal=changelog
  ###########
  # WARNING #
  ###########
  # "changes" must be the last section in this file, because a CI job clean it after each release
  ###########
  artifacthub.io/changes: |
    - kind: added
      description: 'Add support of heartbeat delay for the gateway'
    - kind: fixed
      description: 'add missing haproxy mapping attribute'
      links:
        - name: Github Issue
          url: https://github.com/gravitee-io/issues/issues/10027
    - kind: changed
      description: 'Add support for new OpenTelemetry feature. BREAKING CHANGE: gravitee.services.tracing block of configuration has been replaced by gravitee.services.opentelemetry.'
    - kind: fixed
      description: 'allow users to overwrite the Elasticsearch or Opensearch rollover alias property name'
      links:
        - name: Github Issue
          url: https://github.com/gravitee-io/issues/issues/10100
    - kind: fixed
      description: 'allow users to limit documentation content size in audit page when importing an API'
      links:
        - name: Github Issue
          url: https://github.com/gravitee-io/issues/issues/10117
