apiVersion: v1
name: apim
# Also update CHANGELOG.md
version: 4.1.7
appVersion: 4.1.7
description: Official Gravitee.io Helm chart for API Management
home: https://gravitee.io
sources:
  - https://github.com/gravitee-io
icon: https://avatars2.githubusercontent.com/u/12655666?s=200&v=4
keywords:
  - gravitee.io
  - gravitee
  - graviteeio 
  - API
  - API Management
kubeVersion: ">=1.14.0-0"
annotations:
  # List of changes for the release in artifacthub.io
  # https://artifacthub.io/packages/helm/graviteeio/apim?modal=changelog
  artifacthub.io/changes: |
    - 'Added gateway.services.core.http.ssl.keystore.password'
    - 'fix helm backward compatibility during helm upgrade without `common` field'
    - 'Added default preStop command on ui and portal'
    - 'Changes: Helm Chart is no longer compatible with Helm version prior to 3.10'

