dependencies:
  - name: elasticsearch
    version: 19.10.9
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: mongodb
    version: 13.16.4
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
